import 'package:flutter/material.dart';
import 'package:fluttericon/font_awesome_icons.dart';
import 'package:fluttericon/linearicons_free_icons.dart';

class AppIcons {
  static const IconData add = Icons.add;
  static const IconData close = Icons.close;
  static const IconData questionMark = Icons.question_mark_rounded;
  static const IconData check = Icons.check_rounded;
  static const IconData radioButton = Icons.radio_button_checked_rounded;
  static const IconData emptyCircle = Icons.circle_outlined;
  static const IconData checkCircle = Icons.check_circle_rounded;
  static const IconData outlineCheckCircle = Icons.check_circle_outline_rounded;
  static const IconData keyboardArrowBack = Icons.keyboard_backspace_rounded;
  static const IconData keyboardArrowForward = Icons.arrow_forward_rounded;
  static const IconData arrowDown = Icons.keyboard_arrow_down;
  static const IconData lock = Icons.lock_outline_rounded;
  static const IconData chat = Icons.mark_unread_chat_alt_rounded;
  static const IconData addPerson = Icons.person_add_outlined;
  static const IconData arrowUp = Icons.keyboard_arrow_up_rounded;
  static const IconData arrowBack = Icons.keyboard_arrow_left_rounded;
  static const IconData person = Icons.person;
  static const IconData arrowForward = Icons.keyboard_arrow_right_rounded;
  static const IconData mail = Icons.mail_outline_rounded;
  static const IconData home = Icons.home_rounded;
  static const IconData chart = Icons.bar_chart_rounded;
  static const IconData eye = Icons.remove_red_eye_outlined;
  static const IconData copy = Icons.copy_rounded;
  static const IconData eyeClose = Icons.visibility_off_outlined;
  static const IconData fingerprint = Icons.fingerprint_rounded;
  static const IconData moreHorizontal = Icons.more_horiz_rounded;
  static const IconData search = Icons.search_rounded;
  static const IconData star = Icons.star_border_rounded;
  static const IconData filter = Icons.filter_list_rounded;
  static const IconData male = Icons.male_rounded;
  static const IconData female = Icons.female_rounded;
  static const IconData health = Icons.monitor_heart_outlined;
  static const IconData phone = LineariconsFree.phone_handset;
  static const IconData videoCamera = LineariconsFree.camera_video;
  static const IconData delete = Icons.delete_outline_rounded;
  static const IconData send = Icons.send_rounded;
  static const IconData card = Icons.credit_card;
  static const IconData fileUpload = Icons.file_upload_rounded;
  static const IconData info = Icons.info_outline_rounded;
  static const IconData changeCamera = Icons.cameraswitch_rounded;
  static const IconData masterCard = FontAwesome.cc_mastercard;
  static const IconData visaCard = FontAwesome.cc_visa;
}
